# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/healthkowshik.github.io',
                'doc_host': 'https://healthkowshik.github.io',
                'git_url': 'https://github.com/healthkowshik/healthkowshik.github.io',
                'lib_path': 'healthkowshik'},
  'syms': {'healthkowshik.core': {'healthkowshik.core.foo': ('core.html#foo', 'healthkowshik/core.py')}}}
